GET http://localhost:8080/Ablog/SaveArt
Accept: application/json

###
POST http://localhost:8080/Ablog/SaveArt
Content-Type: application/json

{
  "ArtName": "测试题目",
  "ArtText": "测试正文",
  "Type": "测试类型"
}

###
